import type { BudgetCategory } from "./types";
import { UtensilsCrossed, Wheat, Carrot, Apple, Coffee, Cross, Handshake, Truck } from "lucide-react";

export const initialBudgetData: BudgetCategory[] = [
    {
      id: "cat-1",
      name: "Meat",
      icon: UtensilsCrossed,
      total: 0,
      order: 1,
      items: [
        { id: "item-1-1", name: "Lamb", metric: "per kg", quantity: 100, unitPrice: 185, total: 0, comment: "" },
        { id: "item-1-2", name: "Beef", metric: "per kg", quantity: 50, unitPrice: 175, total: 0, comment: "" },
        { id: "item-1-3", name: "Chicken", metric: "per kg", quantity: 35, unitPrice: 85, total: 0, comment: "" },
        { id: "item-1-4", name: "Pork", metric: "per kg", quantity: 50, unitPrice: 120, total: 0, comment: "" },
      ],
    },
    {
      id: "cat-2",
      name: "Starch",
      icon: Wheat,
      total: 0,
      order: 2,
      items: [
        { id: "item-2-1", name: "Bread", metric: "per loaf", quantity: 40, unitPrice: 20, total: 0, comment: "" },
        { id: "item-2-2", name: "Samp (Umngqusho)", metric: "10kg", quantity: 5, unitPrice: 150, total: 0, comment: "" },
        { id: "item-2-3", name: "Beans", metric: "10kg", quantity: 3, unitPrice: 350, total: 0, comment: "" },
        { id: "item-2-4", name: "Rice", metric: "10 kg", quantity: 5, unitPrice: 175, total: 0, comment: "" },
        { id: "item-2-5", name: "Mealie Meal", metric: "10 kg", quantity: 4, unitPrice: 140, total: 0, comment: "" },
      ],
    },
    {
      id: "cat-3",
      name: "Vegetables",
      icon: Carrot,
      total: 0,
      order: 3,
      items: [
        { id: "item-3-1", name: "Cabbage", metric: "8 heads", quantity: 4, unitPrice: 200, total: 0, comment: "" },
        { id: "item-3-2", name: "Potatoes", metric: "10kg", quantity: 5, unitPrice: 45, total: 0, comment: "" },
        { id: "item-3-3", name: "Carrot", metric: "10kg", quantity: 4, unitPrice: 85, total: 0, comment: "" },
        { id: "item-3-4", name: "Onion", metric: "10kg", quantity: 4, unitPrice: 175, total: 0, comment: "" },
        { id: "item-3-5", name: "Potatoes", metric: "10kg", quantity: 4, unitPrice: 200, total: 0, comment: "" },
      ],
    },
    {
      id: "cat-4",
      name: "Fruit",
      icon: Apple,
      total: 0,
      order: 4,
      items: [
        { id: "item-4-1", name: "Apples", metric: "per box", quantity: 3, unitPrice: 225, total: 0, comment: "" },
        { id: "item-4-2", name: "Banana", metric: "per box", quantity: 3, unitPrice: 150, total: 0, comment: "" },
        { id: "item-4-3", name: "Pears", metric: "per box", quantity: 3, unitPrice: 145, total: 0, comment: "" },
        { id: "item-4-4", name: "Watermelon", metric: "each", quantity: 10, unitPrice: 75, total: 0, comment: "" },
        { id: "item-4-5", name: "Oranges", metric: "per box", quantity: 5, unitPrice: 35, total: 0, comment: "" },
      ],
    },
    {
      id: "cat-5",
      name: "Refreshments",
      icon: Coffee,
      total: 0,
      order: 5,
      items: [
        { id: "item-5-1", name: "Coffee", metric: "750g", quantity: 3, unitPrice: 120, total: 0, comment: "" },
        { id: "item-5-2", name: "Teabag", metric: "100's", quantity: 3, unitPrice: 50, total: 0, comment: "" },
        { id: "item-5-3", name: "Milk", metric: "6x1L", quantity: 10, unitPrice: 125, total: 0, comment: "" },
        { id: "item-5-4", name: "Sugar", metric: "10kg", quantity: 4, unitPrice: 260, total: 0, comment: "" },
        { id: "item-5-5", name: "Bottled Water", metric: "24 of 300ml", quantity: 5, unitPrice: 125, total: 0, comment: "" },
        { id: "item-5-6", name: "Juice", metric: "25 of 300ml", quantity: 4, unitPrice: 200, total: 0, comment: "" },
        { id: "item-5-7", name: "Carbonated Drink", metric: "6 of 2L", quantity: 10, unitPrice: 140, total: 0, comment: "" },
      ],
    },
    {
        id: "cat-6",
        name: "Deceased",
        icon: Cross,
        total: 0,
        order: 6,
        items: [
            { id: "item-6-1", name: "Municipal Grave fees", metric: "per item", quantity: 1, unitPrice: 1500, total: 0, comment: "" },
            { id: "item-6-2", name: "Coffin", metric: "per item", quantity: 1, unitPrice: 10000, total: 0, comment: "" },
            { id: "item-6-3", name: "Coffin Stand", metric: "per day", quantity: 1, unitPrice: 650, total: 0, comment: "" },
            { id: "item-6-4", name: "Grave digging", metric: "per item", quantity: 1, unitPrice: 1200, total: 0, comment: "" },
            { id: "item-6-5", name: "Grave filling / building", metric: "per item", quantity: 1, unitPrice: 500, total: 0, comment: "" },
            { id: "item-6-6", name: "Tombstone", metric: "per item", quantity: 1, unitPrice: 3500, total: 0, comment: "" },
            { id: "item-6-7", name: "Hearse", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "" },
            { id: "item-6-8", name: "Wreath / Flowers", metric: "per item", quantity: 3, unitPrice: 150, total: 0, comment: "" },
            { id: "item-6-9", name: "Suits / Dress", metric: "per item", quantity: 1, unitPrice: 1000, total: 0, comment: "" },
            { id: "item-6-10", name: "Blanket", metric: "per item", quantity: 1, unitPrice: 250, total: 0, comment: "" },
            { id: "item-6-11", name: "Body Travel", metric: "per item", quantity: 0, unitPrice: 6500, total: 0, comment: "" },
        ],
    },
    {
        id: "cat-7",
        name: "Service",
        icon: Handshake,
        total: 0,
        order: 7,
        items: [
            { id: "item-7-6", name: "Gas Stove / Burner", metric: "per item", quantity: 1, unitPrice: 500, total: 0, comment: "" },
            { id: "item-7-7", name: "Imbiza / Pots", metric: "per item", quantity: 6, unitPrice: 100, total: 0, comment: "" },
            { id: "item-7-8", name: "Plates", metric: "per item", quantity: 40, unitPrice: 10, total: 0, comment: "" },
            { id: "item-7-9", name: "Takeaway plate", metric: "75 pcs", quantity: 1, unitPrice: 100, total: 0, comment: "" },
            { id: "item-7-10", name: "Spoons", metric: "10 pkt", quantity: 10, unitPrice: 20, total: 0, comment: "" },
            { id: "item-7-11", name: "Coffee Mugs", metric: "12 pack", quantity: 5, unitPrice: 200, total: 0, comment: "" },
            { id: "item-7-12", name: "Funeral Program", metric: "per item", quantity: 50, unitPrice: 15, total: 0, comment: "" },
            { id: "item-7-18", name: "Videographer", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "" },
            { id: "item-7-19", name: "Pastor", metric: "per day", quantity: 1, unitPrice: 3000, total: 0, comment: "" },
            { id: "item-7-20", name: "Church Quire", metric: "per day", quantity: 1, unitPrice: 3000, total: 0, comment: "" },
        ],
    },
    {
        id: "cat-8",
        name: "Logistics",
        icon: Truck,
        total: 0,
        order: 8,
        items: [
            { id: "item-8-1", name: "Slaughters", metric: "per day", quantity: 5, unitPrice: 100, total: 0, comment: "" },
            { id: "item-8-2", name: "Cookers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "" },
            { id: "item-8-3", name: "Bakers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "" },
            { id: "item-8-4", name: "Bakkie Hire", metric: "per day", quantity: 1, unitPrice: 650, total: 0, comment: "" },
            { id: "item-8-5", name: "Bus / Taxi", metric: "per day", quantity: 0, unitPrice: 1500, total: 0, comment: "" },
            { id: "item-7-1", name: "Tent", metric: "per item", quantity: 1, unitPrice: 1000, total: 0, comment: "" },
            { id: "item-7-2", name: "Tables", metric: "per item", quantity: 4, unitPrice: 150, total: 0, comment: "" },
            { id: "item-7-3", name: "Chairs", metric: "per item", quantity: 50, unitPrice: 15, total: 0, comment: "" },
            { id: "item-7-4", name: "Mobile Fridge", metric: "per item", quantity: 1, unitPrice: 2000, total: 0, comment: "" },
            { id: "item-7-5", name: "Mobile Toilet", metric: "per item", quantity: 3, unitPrice: 1000, total: 0, comment: "" },
        ],
    },
];
