import type { BudgetCategory } from "../types";

export const funeralBudgetData: BudgetCategory[] = [
  {
    id: "catering",
    name: "Catering",
    total: 0,
    order: 1,
    items: [],
    subCategories: [
      {
        id: "cat-1",
        name: "Meat",
        total: 0,
        order: 1,
        items: [
          { id: "funeral-meat-1", name: "Lamb", metric: "per kg", quantity: 100, unitPrice: 185, total: 0, comment: "", is_template: true },
          { id: "funeral-meat-2", name: "Beef", metric: "per kg", quantity: 50, unitPrice: 175, total: 0, comment: "", is_template: true },
          { id: "funeral-meat-3", name: "Chicken", metric: "per kg", quantity: 35, unitPrice: 85, total: 0, comment: "", is_template: true },
          { id: "funeral-meat-4", name: "Pork", metric: "per kg", quantity: 50, unitPrice: 120, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "cat-2",
        name: "Starch",
        total: 0,
        order: 2,
        items: [
          { id: "funeral-starch-1", name: "Bread", metric: "per loaf", quantity: 50, unitPrice: 20, total: 0, comment: "", is_template: true },
          { id: "funeral-starch-2", name: "Samp", metric: "10kg", quantity: 5, unitPrice: 150, total: 0, comment: "", is_template: true },
          { id: "funeral-starch-3", name: "Beans", metric: "10kg", quantity: 3, unitPrice: 350, total: 0, comment: "", is_template: true },
          { id: "funeral-starch-4", name: "Rice", metric: "10 kg", quantity: 5, unitPrice: 175, total: 0, comment: "", is_template: true },
          { id: "funeral-starch-5", name: "Mealie Meal", metric: "10 kg", quantity: 4, unitPrice: 140, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "cat-3",
        name: "Vegetables",
        total: 0,
        order: 3,
        items: [
          { id: "funeral-veg-1", name: "Cabbage", metric: "8 heads", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
          { id: "funeral-veg-2", name: "Potatoes", metric: "10kg", quantity: 5, unitPrice: 45, total: 0, comment: "", is_template: true },
          { id: "funeral-veg-3", name: "Carrot", metric: "10kg", quantity: 4, unitPrice: 85, total: 0, comment: "", is_template: true },
          { id: "funeral-veg-4", name: "Onion", metric: "10kg", quantity: 4, unitPrice: 175, total: 0, comment: "", is_template: true },
          { id: "funeral-veg-5", name: "Tomatoes", metric: "10kg", quantity: 6, unitPrice: 195, total: 0, comment: "", is_template: true },
          { id: "funeral-veg-6", name: "Potatoes", metric: "10kg", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "cat-4",
        name: "Fruit",
        total: 0,
        order: 4,
        items: [
          { id: "funeral-fruit-1", name: "Apples", metric: "per box", quantity: 3, unitPrice: 225, total: 0, comment: "", is_template: true },
          { id: "funeral-fruit-2", name: "Banana", metric: "per box", quantity: 3, unitPrice: 150, total: 0, comment: "", is_template: true },
          { id: "funeral-fruit-3", name: "Pears", metric: "per box", quantity: 3, unitPrice: 145, total: 0, comment: "", is_template: true },
          { id: "funeral-fruit-4", name: "Watermelon", metric: "each", quantity: 10, unitPrice: 75, total: 0, comment: "", is_template: true },
          { id: "funeral-fruit-5", name: "Oranges", metric: "per box", quantity: 5, unitPrice: 35, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "cat-5",
        name: "Refreshments",
        total: 0,
        order: 5,
        items: [
          { id: "funeral-refresh-1", name: "Coffee", metric: "750g", quantity: 3, unitPrice: 120, total: 0, comment: "", is_template: true },
          { id: "funeral-refresh-2", name: "Teabag", metric: "100's", quantity: 3, unitPrice: 50, total: 0, comment: "", is_template: true },
          { id: "funeral-refresh-3", name: "Milk", metric: "6x1L", quantity: 10, unitPrice: 125, total: 0, comment: "", is_template: true },
          { id: "funeral-refresh-4", name: "Sugar", metric: "10kg", quantity: 4, unitPrice: 260, total: 0, comment: "", is_template: true },
          { id: "funeral-refresh-5", name: "Bottled Water", metric: "24 of 300ml", quantity: 5, unitPrice: 125, total: 0, comment: "", is_template: true },
          { id: "funeral-refresh-6", name: "Juice", metric: "25 of 300ml", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
          { id: "funeral-refresh-7", name: "Carbonated Drink", metric: "6 of 2L", quantity: 10, unitPrice: 140, total: 0, comment: "", is_template: true },
        ],
      },
    ],
  },
  {
    id: "cat-6",
    name: "Deceased",
    total: 0,
    order: 2,
    items: [
      { id: "funeral-deceased-1", name: "Municipal Grave fees", metric: "per item", quantity: 1, unitPrice: 1500, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-2", name: "Coffin", metric: "per item", quantity: 1, unitPrice: 10000, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-3", name: "Coffin Stand", metric: "per day", quantity: 1, unitPrice: 650, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-4", name: "Grave digging", metric: "per item", quantity: 1, unitPrice: 1200, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-5", name: "Grave filling / building", metric: "per item", quantity: 1, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-6", name: "Tombstone", metric: "per item", quantity: 1, unitPrice: 3500, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-7", name: "Hearse", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-8", name: "Wreath / Flowers", metric: "per item", quantity: 3, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-9", name: "Suits / Dress", metric: "per item", quantity: 1, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-10", name: "Blanket", metric: "per item", quantity: 1, unitPrice: 250, total: 0, comment: "", is_template: true },
      { id: "funeral-deceased-11", name: "Body Travel", metric: "per item", quantity: 0, unitPrice: 6500, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "cat-7",
    name: "Service",
    total: 0,
    order: 3,
    items: [
      { id: "funeral-service-1", name: "Gas Stove / Burner", metric: "per item", quantity: 2, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "funeral-service-2", name: "Cookware hire", metric: "per item", quantity: 8, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "funeral-service-3", name: "Tableware hire", metric: "4 set", quantity: 40, unitPrice: 50, total: 0, comment: "", is_template: true },
      { id: "funeral-service-4", name: "Takeaway plate", metric: "75 pcs", quantity: 2, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "funeral-service-5", name: "Cutlery hire", metric: "4 set", quantity: 40, unitPrice: 30, total: 0, comment: "", is_template: true },
      { id: "funeral-service-6", name: "Table-Deco", metric: "per table", quantity: 10, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "funeral-service-7", name: "Funeral Program", metric: "per copy", quantity: 50, unitPrice: 15, total: 0, comment: "", is_template: true },
      { id: "funeral-service-8", name: "Videographer", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
      { id: "funeral-service-9", name: "Pastor", metric: "per day", quantity: 1, unitPrice: 3000, total: 0, comment: "", is_template: true },
      { id: "funeral-service-10", name: "Church Choir", metric: "per day", quantity: 1, unitPrice: 3000, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "cat-8",
    name: "Logistics",
    total: 0,
    order: 4,
    items: [
      { id: "funeral-logistics-1", name: "BraaiMaster", metric: "per day", quantity: 5, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-2", name: "Cookers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-3", name: "Bakers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-4", name: "Bakkie Hire", metric: "per day", quantity: 1, unitPrice: 650, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-5", name: "Bus/Taxi", metric: "per day", quantity: 0, unitPrice: 1500, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-6", name: "Tent", metric: "per day", quantity: 1, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-7", name: "Chairs", metric: "per day", quantity: 10, unitPrice: 50, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-8", name: "Tables", metric: "per day", quantity: 2, unitPrice: 80, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-9", name: "Mobile Toilets", metric: "per day", quantity: 1, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "funeral-logistics-10", name: "Photographer", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
    ],
  },
];
