import type { BudgetCategory } from "../types";

export const umemuloBudgetData: BudgetCategory[] = [
  {
    id: "attire-m",
    name: "Traditional attire",
    total: 0,
    order: 1,
    items: [],
    subCategories: [
      {
        id: "intombi",
        name: "iNtombi",
        total: 0,
        order: 1,
        items: [
          { id: "umemulo-intombi-1", name: "Isidwaba / Isigcege", metric: "each", quantity: 1, unitPrice: 1500, total: 0, comment: "(Short Traditional skirt)", is_template: true },
          { id: "umemulo-intombi-2", name: "Ibheshu", metric: "each", quantity: 1, unitPrice: 1800, total: 0, comment: "(Rear covering)", is_template: true },
          { id: "umemulo-intombi-3", name: "Beaded Bra", metric: "each", quantity: 1, unitPrice: 950, total: 0, comment: "", is_template: true },
          { id: "umemulo-intombi-4", name: "Imiqhele", metric: "each", quantity: 1, unitPrice: 350, total: 0, comment: "(Headband / Crown)", is_template: true },
          { id: "umemulo-intombi-5", name: "Izinjoloba", metric: "each", quantity: 1, unitPrice: 350, total: 0, comment: "(Ankle rattles)", is_template: true },
          { id: "umemulo-intombi-6", name: "Imigoxo", metric: "each", quantity: 1, unitPrice: 400, total: 0, comment: "(Beaded Necklace)", is_template: true },
          { id: "umemulo-intombi-7", name: "Vincu", metric: "each", quantity: 1, unitPrice: 350, total: 0, comment: "(Arm bands)", is_template: true },
          { id: "umemulo-intombi-8", name: "Ubuhlalu", metric: "each", quantity: 1, unitPrice: 500, total: 0, comment: "(Waist beads)", is_template: true },
          { id: "umemulo-intombi-9", name: "Umkhonto", metric: "each", quantity: 1, unitPrice: 1000, total: 0, comment: "(Spear)", is_template: true },
        ],
      },
      {
        id: "umama",
        name: "uMama weNtombi",
        total: 0,
        order: 2,
        items: [
          { id: "umemulo-umama-1", name: "Isidwaba", metric: "each", quantity: 1, unitPrice: 3000, total: 0, comment: "(Long leather skirt)", is_template: true },
          { id: "umemulo-umama-2", name: "Isicholo", metric: "each", quantity: 1, unitPrice: 600, total: 0, comment: "(Traditional hat)", is_template: true },
          { id: "umemulo-umama-3", name: "iBhayi", metric: "each", quantity: 1, unitPrice: 400, total: 0, comment: "(Shawl)", is_template: true },
          { id: "umemulo-umama-4", name: "Imigoxo", metric: "each", quantity: 1, unitPrice: 700, total: 0, comment: "(Beaded Necklace)", is_template: true },
          { id: "umemulo-umama-5", name: "iDuku", metric: "each", quantity: 1, unitPrice: 450, total: 0, comment: "(Headscarf)", is_template: true },
        ],
      },
      {
        id: "ubaba",
        name: "uBaba weNtombi",
        total: 0,
        order: 3,
        items: [
          { id: "umemulo-ubaba-1", name: "Ibheshu", metric: "each", quantity: 1, unitPrice: 1800, total: 0, comment: "(Rear Apron)", is_template: true },
          { id: "umemulo-ubaba-2", name: "uMqhele", metric: "each", quantity: 1, unitPrice: 650, total: 0, comment: "(Headband)", is_template: true },
          { id: "umemulo-ubaba-3", name: "Isinene", metric: "each", quantity: 1, unitPrice: 950, total: 0, comment: "(Front covering)", is_template: true },
          { id: "umemulo-ubaba-4", name: "Animal skin vest", metric: "each", quantity: 1, unitPrice: 1650, total: 0, comment: "or chest band", is_template: true },
          { id: "umemulo-ubaba-5", name: "Isihlangu", metric: "each", quantity: 1, unitPrice: 2200, total: 0, comment: "(Shield)", is_template: true },
          { id: "umemulo-ubaba-6", name: "IWisa", metric: "each", quantity: 1, unitPrice: 1000, total: 0, comment: "(Spear or Knobkerrie)", is_template: true },
        ],
      },
      {
        id: "abadala",
        name: "Abadala (uGogo, uMkhulu, etc.)",
        total: 0,
        order: 4,
        items: [],
        subCategories: [
          {
            id: "abesimame",
            name: "AbesiMame",
            total: 0,
            order: 1,
            items: [
              { id: "umemulo-abesimame-1", name: "Isidwaba", metric: "per person", quantity: 4, unitPrice: 1350, total: 0, comment: "(Long full skirt)", is_template: true },
              { id: "umemulo-abesimame-2", name: "iBhayi", metric: "per person", quantity: 4, unitPrice: 500, total: 0, comment: "(Shawl/Blanket)", is_template: true },
              { id: "umemulo-abesimame-3", name: "iDuku", metric: "per person", quantity: 4, unitPrice: 350, total: 0, comment: "(Headscarf)", is_template: true },
              { id: "umemulo-abesimame-4", name: "Imigoxo", metric: "per person", quantity: 4, unitPrice: 500, total: 0, comment: "(Beaded Necklace)", is_template: true },
            ],
          },
          {
            id: "abesilisa",
            name: "AbeSilisa",
            total: 0,
            order: 2,
            items: [
              { id: "umemulo-abesilisa-1", name: "Ibheshu", metric: "per person", quantity: 4, unitPrice: 1500, total: 0, comment: "(Rear Apron)", is_template: true },
              { id: "umemulo-abesilisa-2", name: "uMqhele", metric: "per person", quantity: 4, unitPrice: 400, total: 0, comment: "(Headband)", is_template: true },
              { id: "umemulo-abesilisa-3", name: "IWisa", metric: "per person", quantity: 4, unitPrice: 550, total: 0, comment: "(Knobkerrie)", is_template: true },
            ],
          },
        ],
      },
      {
        id: "amantombazane",
        name: "AmaNtombazane",
        total: 0,
        order: 5,
        items: [
          { id: "umemulo-amantombazane-1", name: "Short Beaded Skirts", metric: "per person", quantity: 3, unitPrice: 650, total: 0, comment: "", is_template: true },
          { id: "umemulo-amantombazane-2", name: "Colorful beadwork", metric: "per person", quantity: 3, unitPrice: 650, total: 0, comment: "", is_template: true },
          { id: "umemulo-amantombazane-3", name: "Beaded tops", metric: "per person", quantity: 3, unitPrice: 700, total: 0, comment: "", is_template: true },
          { id: "umemulo-amantombazane-4", name: "Ankle bands", metric: "per person", quantity: 3, unitPrice: 250, total: 0, comment: "", is_template: true },
          { id: "umemulo-amantombazane-5", name: "Bracelets", metric: "per person", quantity: 3, unitPrice: 250, total: 0, comment: "", is_template: true },
          { id: "umemulo-amantombazane-6", name: "Headbands", metric: "per person", quantity: 3, unitPrice: 300, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "abafana",
        name: "AbaFana",
        total: 0,
        order: 6,
        items: [
          { id: "umemulo-abafana-1", name: "Ibheshu", metric: "per person", quantity: 3, unitPrice: 1200, total: 0, comment: "(Rear Apron)", is_template: true },
          { id: "umemulo-abafana-2", name: "uMqhele", metric: "per person", quantity: 3, unitPrice: 350, total: 0, comment: "(Headband)", is_template: true },
          { id: "umemulo-abafana-3", name: "Chest bands", metric: "per person", quantity: 3, unitPrice: 300, total: 0, comment: "", is_template: true },
          { id: "umemulo-abafana-4", name: "Ankle bands", metric: "per person", quantity: 3, unitPrice: 200, total: 0, comment: "", is_template: true },
          { id: "umemulo-abafana-5", name: "Sticks", metric: "per person", quantity: 3, unitPrice: 350, total: 0, comment: "", is_template: true },
          { id: "umemulo-abafana-6", name: "Shields", metric: "per person", quantity: 3, unitPrice: 750, total: 0, comment: "", is_template: true },
        ],
      },
    ],
  },
  {
    id: "meat-m",
    name: "Livestock / Meat",
    total: 0,
    order: 2,
    items: [
      { id: "umemulo-meat-1", name: "Cow", metric: "per cow", quantity: 1, unitPrice: 15000, total: 0, comment: "", is_template: true },
      { id: "umemulo-meat-2", name: "Chicken", metric: "5 kg", quantity: 5, unitPrice: 350, total: 0, comment: "", is_template: true },
      { id: "umemulo-meat-3", name: "Lamb", metric: "per kg", quantity: 100, unitPrice: 75, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "starch-m",
    name: "Starch",
    total: 0,
    order: 3,
    items: [
      { id: "umemulo-starch-1", name: "Bread", metric: "per loaf", quantity: 40, unitPrice: 20, total: 0, comment: "", is_template: true },
      { id: "umemulo-starch-2", name: "Samp (Umngqusho)", metric: "10kg", quantity: 5, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "umemulo-starch-3", name: "Beans", metric: "10kg", quantity: 3, unitPrice: 350, total: 0, comment: "", is_template: true },
      { id: "umemulo-starch-4", name: "Rice", metric: "10 kg", quantity: 5, unitPrice: 175, total: 0, comment: "", is_template: true },
      { id: "umemulo-starch-5", name: "Mealie Meal", metric: "10 kg", quantity: 4, unitPrice: 140, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "veg-m",
    name: "Vegetables",
    total: 0,
    order: 4,
    items: [
      { id: "umemulo-veg-1", name: "Cabbage", metric: "8 heads", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "umemulo-veg-2", name: "Potatoes", metric: "10kg", quantity: 5, unitPrice: 45, total: 0, comment: "", is_template: true },
      { id: "umemulo-veg-3", name: "Carrot", metric: "10kg", quantity: 4, unitPrice: 85, total: 0, comment: "", is_template: true },
      { id: "umemulo-veg-4", name: "Onion", metric: "10kg", quantity: 4, unitPrice: 175, total: 0, comment: "", is_template: true },
      { id: "umemulo-veg-5", name: "Potatoes", metric: "10kg", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "fruit-m",
    name: "Fruit",
    total: 0,
    order: 5,
    items: [
      { id: "umemulo-fruit-1", name: "Apples", metric: "per box", quantity: 2, unitPrice: 225, total: 0, comment: "", is_template: true },
      { id: "umemulo-fruit-2", name: "Banana", metric: "per box", quantity: 3, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "umemulo-fruit-3", name: "Oranges", metric: "10 kg", quantity: 5, unitPrice: 30, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "ref-m",
    name: "Refreshments",
    total: 0,
    order: 6,
    items: [
      { id: "umemulo-refresh-1", name: "Coffee", metric: "750g", quantity: 3, unitPrice: 120, total: 0, comment: "", is_template: true },
      { id: "umemulo-refresh-2", name: "Teabag", metric: "100s", quantity: 3, unitPrice: 50, total: 0, comment: "", is_template: true },
      { id: "umemulo-refresh-3", name: "Milk", metric: "6x1L", quantity: 10, unitPrice: 125, total: 0, comment: "", is_template: true },
      { id: "umemulo-refresh-4", name: "Sugar", metric: "10kg", quantity: 4, unitPrice: 260, total: 0, comment: "", is_template: true },
      { id: "umemulo-refresh-5", name: "Bottled Water", metric: "24 of 300ml", quantity: 5, unitPrice: 125, total: 0, comment: "", is_template: true },
      { id: "umemulo-refresh-6", name: "Juice", metric: "25 of 300ml", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "umemulo-refresh-7", name: "Carbonated Drink", metric: "6 of 2L", quantity: 10, unitPrice: 140, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "imp-m",
    name: "Implements",
    total: 0,
    order: 7,
    items: [
      { id: "umemulo-implements-1", name: "Tent", metric: "per item", quantity: 1, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-2", name: "Tables", metric: "per item", quantity: 4, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-3", name: "Chairs", metric: "per item", quantity: 50, unitPrice: 15, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-4", name: "Mobile Fridge", metric: "per item", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-5", name: "Mobile Toilet", metric: "per item", quantity: 3, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-6", name: "Gas Stove / Burner", metric: "per item", quantity: 1, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-7", name: "Imbiza / Pots", metric: "per item", quantity: 6, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-8", name: "Plates", metric: "per item", quantity: 40, unitPrice: 10, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-9", name: "Takeaway plate", metric: "75 pcs", quantity: 1, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-10", name: "Spoons", metric: "10 pkt", quantity: 10, unitPrice: 20, total: 0, comment: "", is_template: true },
      { id: "umemulo-implements-11", name: "Coffee Mugs", metric: "12 pack", quantity: 5, unitPrice: 200, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "exe-m",
    name: "Event Execution",
    total: 0,
    order: 8,
    items: [
      { id: "umemulo-execution-1", name: "Slaughters", metric: "per day", quantity: 5, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "umemulo-execution-2", name: "Cookers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umemulo-execution-3", name: "Bakers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umemulo-execution-4", name: "Bakkie Hire", metric: "per day", quantity: 1, unitPrice: 650, total: 0, comment: "", is_template: true },
      { id: "umemulo-execution-5", name: "Videographer", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
    ],
  },
];
