import type { BudgetCategory } from "../types";

export const umGidiBudgetData: BudgetCategory[] = [
  {
    id: "clothing",
    name: "Iimpahla",
    total: 0,
    order: 1,
    items: [],
    subCategories: [
      {
        id: "umkhwetha",
        name: "Umkhwetha (The Boy)",
        total: 0,
        order: 1,
        items: [
          { id: "umgidi-umkhwetha-1", name: "Initiation Certification", metric: "per event", quantity: 1, unitPrice: 950, total: 0, comment: "", is_template: true },
          { id: "umgidi-umkhwetha-2", name: "Ingubo yongena", metric: "per item", quantity: 1, unitPrice: 450, total: 0, comment: "", is_template: true },
          { id: "umgidi-umkhwetha-3", name: "Ingcibi", metric: "per event", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
          { id: "umgidi-umkhwetha-4", name: "Ikhankatha", metric: "per event", quantity: 1, unitPrice: 3000, total: 0, comment: "", is_template: true },
          { id: "umgidi-umkhwetha-5", name: "Ibhuma", metric: "per event", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "ikrwala",
        name: "iKrwala (The New Man)",
        total: 0,
        order: 2,
        items: [
          { id: "umgidi-ikrwala-1", name: "Ingubo Yophuma", metric: "per item", quantity: 1, unitPrice: 450, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-2", name: "Ikhetshemiya", metric: "per item", quantity: 2, unitPrice: 300, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-3", name: "Imbola", metric: "per item", quantity: 5, unitPrice: 40, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-4", name: "Shirts", metric: "per item", quantity: 3, unitPrice: 350, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-5", name: "Trousers/Pants", metric: "per item", quantity: 2, unitPrice: 750, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-6", name: "Shoes", metric: "per item", quantity: 2, unitPrice: 1500, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-7", name: "Socks", metric: "per item", quantity: 4, unitPrice: 50, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-8", name: "Chefu", metric: "per item", quantity: 3, unitPrice: 75, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-9", name: "Cap/Hat", metric: "per item", quantity: 2, unitPrice: 750, total: 0, comment: "", is_template: true },
          { id: "umgidi-ikrwala-10", name: "Underwear", metric: "per item", quantity: 5, unitPrice: 100, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "izibanzana",
        name: "Izibanzana",
        total: 0,
        order: 3,
        items: [
          { id: "umgidi-izibanzana-1", name: "Umbaco", metric: "per set", quantity: 1, unitPrice: 5000, total: 0, comment: "", is_template: true },
          { id: "umgidi-izibanzana-2", name: "Paskot", metric: "per item", quantity: 1, unitPrice: 500, total: 0, comment: "", is_template: true },
          { id: "umgidi-izibanzana-3", name: "Qhiya", metric: "per item", quantity: 1, unitPrice: 350, total: 0, comment: "", is_template: true },
          { id: "umgidi-izibanzana-4", name: "Bead art work", metric: "per set", quantity: 1, unitPrice: 350, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "utata",
        name: "Utata",
        total: 0,
        order: 4,
        items: [
          { id: "umgidi-utata-1", name: "Head band", metric: "per item", quantity: 1, unitPrice: 400, total: 0, comment: "", is_template: true },
          { id: "umgidi-utata-2", name: "Beaded stick", metric: "per item", quantity: 1, unitPrice: 400, total: 0, comment: "", is_template: true },
          { id: "umgidi-utata-3", name: "Umbaco", metric: "per set", quantity: 1, unitPrice: 1050, total: 0, comment: "", is_template: true },
        ],
      },
    ],
  },
  {
    id: "refreshments",
    name: "Refreshments",
    total: 0,
    order: 2,
    items: [
      { id: "umgidi-refresh-1", name: "Brandy", metric: "per bottle", quantity: 10, unitPrice: 180, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-2", name: "Whisky / Gin", metric: "per bottle", quantity: 5, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-3", name: "Umqombothi", metric: "100Ls", quantity: 3, unitPrice: 350, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-4", name: "Beer", metric: "Cases", quantity: 10, unitPrice: 250, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-5", name: "Wine", metric: "per bottle", quantity: 10, unitPrice: 75, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-6", name: "Ice", metric: "2kg", quantity: 5, unitPrice: 75, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-7", name: "Coffee", metric: "750g", quantity: 3, unitPrice: 120, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-8", name: "Teabag", metric: "100's", quantity: 3, unitPrice: 50, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-9", name: "Milk", metric: "6x1L", quantity: 10, unitPrice: 125, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-10", name: "Sugar", metric: "10kg", quantity: 4, unitPrice: 260, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-11", name: "Bottled Water", metric: "24 of 300ml", quantity: 5, unitPrice: 125, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-12", name: "Juice", metric: "25 of 300ml", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "umgidi-refresh-13", name: "Fizz Drinks", metric: "2Ls", quantity: 10, unitPrice: 140, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "meat",
    name: "Meat",
    total: 0,
    order: 3,
    items: [
      { id: "umgidi-meat-1", name: "Sheep", metric: "per sheep", quantity: 5, unitPrice: 3000, total: 0, comment: "", is_template: true },
      { id: "umgidi-meat-2", name: "Goat", metric: "per goat", quantity: 1, unitPrice: 4000, total: 0, comment: "", is_template: true },
      { id: "umgidi-meat-3", name: "Cow", metric: "per cow", quantity: 1, unitPrice: 8500, total: 0, comment: "", is_template: true },
      { id: "umgidi-meat-4", name: "Chicken", metric: "5kg", quantity: 10, unitPrice: 250, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "starch",
    name: "Starch",
    total: 0,
    order: 4,
    items: [
      { id: "umgidi-starch-1", name: "Bread", metric: "per loaf", quantity: 40, unitPrice: 20, total: 0, comment: "", is_template: true },
      { id: "umgidi-starch-2", name: "Samp (Umngqusho)", metric: "10kg", quantity: 5, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "umgidi-starch-3", name: "Rice", metric: "10 kg", quantity: 5, unitPrice: 175, total: 0, comment: "", is_template: true },
      { id: "umgidi-starch-4", name: "Mealie Meal", metric: "10 kg", quantity: 4, unitPrice: 140, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "vegetables",
    name: "Vegetables",
    total: 0,
    order: 5,
    items: [
      { id: "umgidi-veg-1", name: "Cabbage", metric: "8 heads", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "umgidi-veg-2", name: "Potatoes", metric: "10kg", quantity: 5, unitPrice: 45, total: 0, comment: "", is_template: true },
      { id: "umgidi-veg-3", name: "Carrot", metric: "10kg", quantity: 4, unitPrice: 85, total: 0, comment: "", is_template: true },
      { id: "umgidi-veg-4", name: "Onion", metric: "10kg", quantity: 4, unitPrice: 175, total: 0, comment: "", is_template: true },
      { id: "umgidi-veg-5", name: "Potatoes (Extra)", metric: "10kg", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "fruit",
    name: "Fruit",
    total: 0,
    order: 6,
    items: [
      { id: "umgidi-fruit-1", name: "Apples", metric: "per box", quantity: 2, unitPrice: 225, total: 0, comment: "", is_template: true },
      { id: "umgidi-fruit-2", name: "Banana", metric: "per box", quantity: 3, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "umgidi-fruit-3", name: "Oranges", metric: "10 kg", quantity: 5, unitPrice: 30, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "implements",
    name: "Implements",
    total: 0,
    order: 7,
    items: [
      { id: "umgidi-implements-1", name: "Tent", metric: "per item", quantity: 1, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-2", name: "Tables", metric: "per item", quantity: 4, unitPrice: 150, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-3", name: "Chairs", metric: "per item", quantity: 50, unitPrice: 15, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-4", name: "Mobile Fridge", metric: "per item", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-5", name: "Mobile Toilet", metric: "per item", quantity: 3, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-6", name: "Gas Stove / Burner", metric: "per item", quantity: 1, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-7", name: "Imbiza / Pots", metric: "per item", quantity: 6, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-8", name: "Plates", metric: "per item", quantity: 40, unitPrice: 10, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-9", name: "Takeaway plate", metric: "75 pcs", quantity: 1, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-10", name: "Spoons", metric: "10 pkt", quantity: 10, unitPrice: 20, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-11", name: "Coffee Mugs", metric: "12 pack", quantity: 5, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-12", name: "Cooler Box", metric: "per item", quantity: 4, unitPrice: 50, total: 0, comment: "", is_template: true },
      { id: "umgidi-implements-13", name: "Spit Braai", metric: "per item", quantity: 2, unitPrice: 1050, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "event-execution",
    name: "Event Execution",
    total: 0,
    order: 8,
    items: [
      { id: "umgidi-execution-1", name: "Abaxheli / Slaughters", metric: "per day", quantity: 5, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-2", name: "Aboji", metric: "per day", quantity: 2, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-3", name: "Abapheki (ebuhlanti)", metric: "per day", quantity: 2, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-4", name: "Abapheki / Cookers", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-5", name: "Ababhaki", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-6", name: "Bakkie Hire", metric: "per day", quantity: 1, unitPrice: 650, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-7", name: "Video Capturing", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-8", name: "Music / DJ", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-9", name: "Imbongi", metric: "per day", quantity: 1, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "umgidi-execution-10", name: "Performers (live band)", metric: "per day", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
    ],
  },
];
