import type { BudgetCategory } from "../types";

export const weddingBudgetData: BudgetCategory[] = [
  {
    id: "venue",
    name: "Venue",
    total: 0,
    order: 1,
    items: [
      { id: "wedding-venue-1", name: "Ceremony Venue", metric: "flat fee", quantity: 1, unitPrice: 15000, total: 0, comment: "Includes seating for 100 guests", is_template: true },
      { id: "wedding-venue-2", name: "Reception Hall", metric: "flat fee", quantity: 1, unitPrice: 25000, total: 0, comment: "Includes tables, chairs, and basic linens", is_template: true },
    ],
  },
  {
    id: "attire",
    name: "Attire",
    total: 0,
    order: 2,
    items: [],
    subCategories: [
      {
        id: "bride",
        name: "Bride",
        total: 0,
        order: 1,
        items: [
          { id: "wedding-bride-1", name: "Wedding Dress", metric: "item", quantity: 1, unitPrice: 12500, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-2", name: "Traditional Dress", metric: "item", quantity: 1, unitPrice: 7500, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-3", name: "Veil/Headpiece", metric: "item", quantity: 1, unitPrice: 1500, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-4", name: "Ring", metric: "item", quantity: 1, unitPrice: 15000, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-5", name: "Necklace & Bracelet", metric: "per set", quantity: 1, unitPrice: 4500, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-6", name: "Makeup", metric: "item", quantity: 1, unitPrice: 2000, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-7", name: "Hairstylist", metric: "item", quantity: 1, unitPrice: 1500, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-8", name: "Footware", metric: "item", quantity: 1, unitPrice: 4500, total: 0, comment: "", is_template: true },
          { id: "wedding-bride-9", name: "Traditional Accessories", metric: "per set", quantity: 1, unitPrice: 4500, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "groom",
        name: "Groom",
        total: 0,
        order: 2,
        items: [
          { id: "wedding-groom-1", name: "Suit/Tuxedo", metric: "item", quantity: 1, unitPrice: 5000, total: 0, comment: "", is_template: true },
          { id: "wedding-groom-2", name: "Ring", metric: "item", quantity: 1, unitPrice: 7500, total: 0, comment: "", is_template: true },
          { id: "wedding-groom-3", name: "Casual Wear", metric: "item", quantity: 1, unitPrice: 4500, total: 0, comment: "", is_template: true },
          { id: "wedding-groom-4", name: "Traditional Wear", metric: "item", quantity: 1, unitPrice: 7500, total: 0, comment: "", is_template: true },
          { id: "wedding-groom-5", name: "Traditional Accessories", metric: "per set", quantity: 1, unitPrice: 1500, total: 0, comment: "", is_template: true },
          { id: "wedding-groom-6", name: "Footware", metric: "pair", quantity: 1, unitPrice: 5500, total: 0, comment: "", is_template: true },
          { id: "wedding-groom-7", name: "Grooming", metric: "item", quantity: 1, unitPrice: 350, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "bridesmaids",
        name: "Bridesmaids & Groomsmen",
        total: 0,
        order: 3,
        items: [
          { id: "wedding-bridal-party-1", name: "Bridesmaid Dresses", metric: "item", quantity: 4, unitPrice: 2000, total: 0, comment: "", is_template: true },
          { id: "wedding-bridal-party-2", name: "Groomsmen Suits", metric: "item", quantity: 4, unitPrice: 1500, total: 0, comment: "", is_template: true },
        ],
      },
    ],
  },
  {
    id: "catering",
    name: "Catering",
    total: 0,
    order: 3,
    items: [],
    subCategories: [
      {
        id: "refreshments",
        name: "Refreshments",
        total: 0,
        order: 1,
        items: [
          { id: "wedding-refresh-1", name: "Coffee", metric: "750g", quantity: 3, unitPrice: 120, total: 0, comment: "", is_template: true },
          { id: "wedding-refresh-2", name: "Teabag", metric: "100's", quantity: 3, unitPrice: 50, total: 0, comment: "", is_template: true },
          { id: "wedding-refresh-3", name: "Milk", metric: "6x1L", quantity: 10, unitPrice: 125, total: 0, comment: "", is_template: true },
          { id: "wedding-refresh-4", name: "Sugar", metric: "10kg", quantity: 4, unitPrice: 260, total: 0, comment: "", is_template: true },
          { id: "wedding-refresh-5", name: "Bottled Water", metric: "24 of 300ml", quantity: 5, unitPrice: 125, total: 0, comment: "", is_template: true },
          { id: "wedding-refresh-6", name: "Juice", metric: "25 of 300ml", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
          { id: "wedding-refresh-7", name: "Carbonated Drink", metric: "6 of 2L", quantity: 10, unitPrice: 140, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "meat",
        name: "Meat",
        total: 0,
        order: 2,
        items: [
          { id: "wedding-meat-1", name: "Lamb", metric: "per kg", quantity: 100, unitPrice: 185, total: 0, comment: "", is_template: true },
          { id: "wedding-meat-2", name: "Beef", metric: "per kg", quantity: 50, unitPrice: 175, total: 0, comment: "", is_template: true },
          { id: "wedding-meat-3", name: "Pork", metric: "per kg", quantity: 50, unitPrice: 120, total: 0, comment: "", is_template: true },
          { id: "wedding-meat-4", name: "Chicken", metric: "per kg", quantity: 35, unitPrice: 85, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "starch",
        name: "Starch",
        total: 0,
        order: 3,
        items: [
          { id: "wedding-starch-1", name: "Bread", metric: "per loaf", quantity: 40, unitPrice: 20, total: 0, comment: "", is_template: true },
          { id: "wedding-starch-2", name: "Samp", metric: "10kg", quantity: 5, unitPrice: 150, total: 0, comment: "", is_template: true },
          { id: "wedding-starch-3", name: "Beans", metric: "10kg", quantity: 3, unitPrice: 350, total: 0, comment: "", is_template: true },
          { id: "wedding-starch-4", name: "Rice", metric: "10 kg", quantity: 5, unitPrice: 175, total: 0, comment: "", is_template: true },
          { id: "wedding-starch-5", name: "Mealie Meal", metric: "10 kg", quantity: 4, unitPrice: 140, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "vegetables",
        name: "Vegetables",
        total: 0,
        order: 4,
        items: [
          { id: "wedding-veg-1", name: "Cabbage", metric: "8 heads", quantity: 4, unitPrice: 200, total: 0, comment: "", is_template: true },
          { id: "wedding-veg-2", name: "Potatoes", metric: "10kg", quantity: 5, unitPrice: 45, total: 0, comment: "", is_template: true },
          { id: "wedding-veg-3", name: "Carrot", metric: "10kg", quantity: 4, unitPrice: 85, total: 0, comment: "", is_template: true },
          { id: "wedding-veg-4", name: "Onion", metric: "10kg", quantity: 4, unitPrice: 175, total: 0, comment: "", is_template: true },
          { id: "wedding-veg-5", name: "Tomatoes", metric: "10kg", quantity: 5, unitPrice: 180, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "fruit",
        name: "Fruit",
        total: 0,
        order: 5,
        items: [
          { id: "wedding-fruit-1", name: "Apples", metric: "per box", quantity: 3, unitPrice: 225, total: 0, comment: "", is_template: true },
          { id: "wedding-fruit-2", name: "Banana", metric: "per box", quantity: 3, unitPrice: 150, total: 0, comment: "", is_template: true },
          { id: "wedding-fruit-3", name: "Oranges", metric: "per sack", quantity: 3, unitPrice: 70, total: 0, comment: "", is_template: true },
          { id: "wedding-fruit-4", name: "Water Melon", metric: "item", quantity: 8, unitPrice: 75, total: 0, comment: "", is_template: true },
          { id: "wedding-fruit-5", name: "Grapes", metric: "per box", quantity: 4, unitPrice: 120, total: 0, comment: "", is_template: true },
          { id: "wedding-fruit-6", name: "Pears", metric: "per box", quantity: 3, unitPrice: 145, total: 0, comment: "", is_template: true },
        ],
      },
      {
        id: "desserts",
        name: "Desserts & Beverages",
        total: 0,
        order: 6,
        items: [
          { id: "wedding-desserts-1", name: "Wedding Cake", metric: "item", quantity: 1, unitPrice: 3000, total: 0, comment: "3-tier cake for 100 guests", is_template: true },
          { id: "wedding-desserts-2", name: "Assorted Desserts", metric: "per serving", quantity: 50, unitPrice: 50, total: 0, comment: "", is_template: true },
          { id: "wedding-desserts-3", name: "Spirits", metric: "item", quantity: 10, unitPrice: 350, total: 0, comment: "", is_template: true },
          { id: "wedding-desserts-4", name: "Wine", metric: "item", quantity: 10, unitPrice: 120, total: 0, comment: "", is_template: true },
          { id: "wedding-desserts-5", name: "Beer & Ciders", metric: "24 pck", quantity: 20, unitPrice: 350, total: 0, comment: "", is_template: true },
        ],
      },
    ],
  },
  {
    id: "service",
    name: "Service",
    total: 0,
    order: 4,
    items: [
      { id: "wedding-service-1", name: "Pre-Nup", metric: "per contract", quantity: 1, unitPrice: 5000, total: 0, comment: "", is_template: true },
      { id: "wedding-service-2", name: "Pastor", metric: "per day", quantity: 1, unitPrice: 3000, total: 0, comment: "", is_template: true },
      { id: "wedding-service-3", name: "Live-band/DJ", metric: "per day", quantity: 1, unitPrice: 3000, total: 0, comment: "", is_template: true },
      { id: "wedding-service-4", name: "Cookware hire", metric: "per item", quantity: 6, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "wedding-service-5", name: "Tableware hire", metric: "per item", quantity: 40, unitPrice: 10, total: 0, comment: "", is_template: true },
      { id: "wedding-service-6", name: "Cutlery hire", metric: "10 pkt", quantity: 10, unitPrice: 20, total: 0, comment: "", is_template: true },
      { id: "wedding-service-7", name: "Table-Deco", metric: "12 pack", quantity: 5, unitPrice: 200, total: 0, comment: "", is_template: true },
      { id: "wedding-service-8", name: "Praise Singer", metric: "per day", quantity: 1, unitPrice: 1500, total: 0, comment: "", is_template: true },
    ],
  },
  {
    id: "logistics",
    name: "Logistics",
    total: 0,
    order: 5,
    items: [
      { id: "wedding-logistics-1", name: "BraaiMaster", metric: "per day", quantity: 5, unitPrice: 100, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-2", name: "Gas-Stoves/Burner", metric: "item", quantity: 2, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-3", name: "Cookers", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-4", name: "Bakers", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-5", name: "Bakkie Hire", metric: "per day", quantity: 1, unitPrice: 950, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-6", name: "MiniBus / Taxi", metric: "per day", quantity: 1, unitPrice: 750, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-7", name: "Tent", metric: "per day", quantity: 1, unitPrice: 1000, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-8", name: "Chairs", metric: "per day", quantity: 60, unitPrice: 35, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-9", name: "Tables", metric: "per day", quantity: 15, unitPrice: 80, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-10", name: "Mobile Toilets", metric: "per day", quantity: 3, unitPrice: 500, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-11", name: "Photographer", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
      { id: "wedding-logistics-12", name: "Videographer", metric: "per day", quantity: 1, unitPrice: 2500, total: 0, comment: "", is_template: true },
    ],
  },
];
